# =============================================================================
# MetalLB ConfigMap
# =============================================================================
# Configuration pour exclure certaines interfaces réseau de l'annonce L2.
# Cela évite les conflits avec les interfaces virtuelles de Docker, Flannel,
# Calico, etc.
# =============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-excludel2
  namespace: metallb-system
data:
  excludel2.yaml: |
    announcedInterfacesToExclude:
      - "^docker.*"
      - "^cbr.*"
      - "^dummy.*"
      - "^virbr.*"
      - "^lxcbr.*"
      - "^veth.*"
      - "^lo$"
      - "^cali.*"
      - "^tunl.*"
      - "^flannel.*"
      - "^kube-ipvs.*"
      - "^cni.*"
      - "^nodelocaldns.*"
      - "^lxc.*"
