# =============================================================================
# Ingress Class
# =============================================================================
# Définit la classe d'ingress "nginx" utilisée par ce controller.
#
# Les Ingress doivent spécifier cette classe avec:
#   ingressClassName: nginx
#
# Ou via l'annotation (déprécié):
#   kubernetes.io/ingress.class: nginx
#
# Pour définir comme classe par défaut, ajoutez l'annotation:
#   ingressclass.kubernetes.io/is-default-class: "true"
# =============================================================================

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: "1.11.1"
  # Décommentez pour définir comme classe par défaut:
  # annotations:
  #   ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx
